# Generated by Django 2.1.15 on 2021-11-24 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
